apiVersion: v1
kind: Service
metadata:
  name: snake-game-service
spec:
  selector:
    app: snake-game
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 5000  # Internal port of the container
  type: LoadBalancer
